Prism/Controllers/CorpusController.cs
/*
    Version Variation Visualisation (VVV)
    http://www.delightedbeauty.org
    
    Copyright (c) Kevin Flanagan, 2012.
    http://www.kftrans.co.uk
  
    This file is part of VVV.

    VVV is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    VVV is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with VVV.  If not, see <http://www.gnu.org/licenses/>.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EblaAPI;
using Prism.Models;
using ICSharpCode.SharpZipLib.Zip;
using System.Xml;
using System.Diagnostics;
using EblaImpl;

namespace Prism.Controllers
{
    [Authorize]
    public class CorpusController : PrismController
    {
        //==============================================
        //
        //  Page rendering
        //
        //==============================================


        public ActionResult Index(string CorpusName)
        {
            try
            {
                // Since they're 'opening' this corpus, store its name in session
                // to make it the 'active' one
                SetActiveCorpus(CorpusName, false);

                return View(GetModel(CorpusName));
            }
            catch (Exception ex)
            {
                string message = "An error occurred while trying to open corpus '" + CorpusName + "': " + ex.Message;
                return RedirectToAction("Error", "Home", new  { message = message });
            }
        }

        private static string _prismactivecorpuscookiename = "prismactivecorpus";
        private static string _prismactivecorpusselectioncookiename = "prismactivecorpusselection";
        private static string _prismsegmentselectioncookiename = "prismsegmentselection";

        private static void SetActiveCorpusSelection(List<string> versions)
        {
            var sb = new System.Text.StringBuilder();
            foreach (var v in versions)
                sb.Append(v + Environment.NewLine);
            var cookie = new HttpCookie(_prismactivecorpusselectioncookiename);
            cookie.Value = System.Web.HttpUtility.UrlPathEncode(sb.ToString());
            //cookie.Value = sb.ToString();
            cookie.Path = "/";
            cookie.Expires = DateTime.Now.AddDays(7);
            System.Web.HttpContext.Current.Response.Cookies.Remove(_prismactivecorpusselectioncookiename);
            System.Web.HttpContext.Current.Response.SetCookie(cookie);

        }

        private static void SetActiveCorpus(string CorpusName, bool noCheck)
        {
            // Is this a change of active corpus?
            if (!noCheck)
                if (string.Compare(GetActiveCorpus(), CorpusName) == 0)
                    return;  // don't regenerate selection info etc.

            //System.Web.HttpContext.Current.Session["prismactivecorpus"] = CorpusName;
            HttpCookie cookie = new HttpCookie(_prismactivecorpuscookiename);
            cookie.Value = System.Web.HttpUtility.UrlPathEncode(CorpusName);
            cookie.Path = "/";
            cookie.Expires = DateTime.Now.AddDays(7);
            //RemoveRequestCookie(_prismactivecorpuscookiename);
            System.Web.HttpContext.Current.Response.Cookies.Remove(_prismactivecorpuscookiename);
            System.Web.HttpContext.Current.Response.SetCookie(cookie);

            if (!string.IsNullOrEmpty(CorpusName))
            {
                var corpus = PrismHelpers.GetCorpus(CorpusName);
                var versions = corpus.GetVersionList();
                SetActiveCorpusSelection(new List<string>(versions));

            }
            else
            {
                SetActiveCorpusSelection(new List<string>());
            }

            //var sb = new System.Text.StringBuilder();
            //foreach (var v in versions)
            //    sb.Append(v + Environment.NewLine);
            //cookie = new HttpCookie(_prismactivecorpusselectioncookiename);
            //cookie.Value = System.Web.HttpUtility.UrlPathEncode( sb.ToString());
            ////cookie.Value = sb.ToString();
            //cookie.Path = "/";
            //cookie.Expires = DateTime.Now.AddDays(7);
            //System.Web.HttpContext.Current.Response.Cookies.Remove(_prismactivecorpusselectioncookiename);
            //System.Web.HttpContext.Current.Response.SetCookie(cookie);

            cookie = new HttpCookie(_prismsegmentselectioncookiename);
            cookie.Value = string.Empty;
            //cookie.Value = sb.ToString();
            cookie.Path = "/";
            cookie.Expires = DateTime.Now.AddDays(7);

            //RemoveRequestCookie(_prismactivecorpusselectioncookiename);
            System.Web.HttpContext.Current.Response.Cookies.Remove(_prismsegmentselectioncookiename);
            System.Web.HttpContext.Current.Response.SetCookie(cookie);

        }

        //static void RemoveRequestCookie(string cookieName)
        //{
        //    var cookie = System.Web.HttpContext.Current.Request.Cookies[cookieName];
        //    if (cookie != null)
        //        cookie.Value = string.Empty;
        //}

        internal static HttpCookie GetLatestCookie(string cookieName)
        {
            //for (int i = 0; i < System.Web.HttpContext.Current.Response.Cookies.Keys.Count; i++)
            //{
            //    if (string.Compare(cookieName, System.Web.HttpContext.Current.Response.Cookies.Keys.Get(i)) == 0)
            //    {
            //        return System.Web.HttpContext.Current.Request.Cookies[cookieName];
            //    }

            //}
            
            foreach (var k in System.Web.HttpContext.Current.Response.Cookies.AllKeys)
                if (string.Compare(cookieName, k) == 0)
                {
                    return System.Web.HttpContext.Current.Response.Cookies[cookieName];
                }

            //var cookie = System.Web.HttpContext.Current.Request.Cookies[_prismactivecorpusselectioncookiename];
            //if (cookie == null || string.IsNullOrEmpty(cookie.Value))
            //    cookie = System.Web.HttpContext.Current.Response.Cookies[_prismactivecorpusselectioncookiename];
            //return cookie;

            return System.Web.HttpContext.Current.Request.Cookies[cookieName];
        }

        public static List<string> GetActiveCorpusSelection()
        {
            string corpusName = GetActiveCorpus();
            if (string.IsNullOrEmpty(corpusName))
                return new List<string>();

            var cookie = GetLatestCookie(_prismactivecorpusselectioncookiename);

            if (cookie == null)
                return new List<string>();
            if (cookie.Value == null)
                return new List<string>();

            //var decoded = System.Web.HttpUtility.UrlDecode(cookie.Value);
            var decoded = System.Uri.UnescapeDataString(cookie.Value);
            var versions = decoded.Split(new char[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);

            // Do all these versions still exist?
            var check = new List<string>();
            try
            {
                var corpus = PrismHelpers.GetCorpus(corpusName);
                var map = new HashSet<string>(corpus.GetVersionList());
                foreach (var v in versions)
                    if (map.Contains(v))
                        check.Add(v);

                if (versions.Length != check.Count)
                {
                    System.Diagnostics.Debug.Assert(versions.Length > check.Count);
                    SetActiveCorpusSelection(check);
                }

            }
            catch (Exception ex)
            {

            }
            return check;

        }

        public static void SetSegmentSelectionList(List<int> list)
        {
            var sb = new System.Text.StringBuilder();
            foreach (var l in list)
            {
                if (sb.Length > 0)
                    sb.Append("-");
                sb.Append(l.ToString());
            }

            var cookie = new HttpCookie(_prismsegmentselectioncookiename);
            cookie.Value = sb.ToString();
            //cookie.Value = sb.ToString();
            cookie.Path = "/";
            cookie.Expires = DateTime.Now.AddDays(7);

            //RemoveRequestCookie(_prismactivecorpusselectioncookiename);
            System.Web.HttpContext.Current.Response.Cookies.Remove(_prismsegmentselectioncookiename);
            System.Web.HttpContext.Current.Response.SetCookie(cookie);

        }

        public static List<int> GetSegmentSelectionList()
        {
            if (string.IsNullOrEmpty(GetActiveCorpus()))
                return new List<int>();

            var cookie = GetLatestCookie(_prismsegmentselectioncookiename);

            if (cookie == null)
                return new List<int>();
            if (cookie.Value == null)
                return new List<int>();

            var idsHash = new HashSet<int>();

            var ids = cookie.Value.Split(new char[] { '-' }, StringSplitOptions.RemoveEmptyEntries);
            foreach (var id in ids)
            {
                int i = 0;
                if (int.TryParse(id, out i))
                    if (!idsHash.Contains(i))
                        idsHash.Add(i);
            }

            return new List<int>(idsHash);

        }

        public static string GetCorpusCaption()
        {
            string corpusname = GetActiveCorpus();
            if (String.IsNullOrEmpty(corpusname))
                return string.Empty;

Prism/Views/Aligner/Index.cshtml
@model Prism.Models.AlignModel

@{
    Layout = "~/Views/Shared/_OldLayout.cshtml";
}



@section TitleContent
{
        @PrismResources.Aligner
    }

    <h2>@PrismResources.Aligner</h2>

    <div style="float:right">@PrismResources.Sync_editor_scroll<input type="checkbox"   id="syncscroll"  /></div>

<div id="divAlignerStatus" class="alignerStatus">
    <div class="alert alert-info" id="txtAlignerStatus"></div>
</div>

<input type="hidden" id="alignerBusy" value="@ViewData[" alignerBusy"]" />
<div id="divLoading">
    <div id="divLoadingInfo">
        <img src="@Url.Content(" ~/Content/img/bar-loader.gif")" width="50" alt="" />
    </div>
</div>


    <input type="hidden" id="basetextSegIDToView" value="@ViewData["basetextSegIDToView"]" />
    <input type="hidden" id="versionSegIDToView" value="@ViewData["versionSegIDToView"]" />
    <table style="width: 100%">
        <tr>
            <td valign="top" style="width:50%">
                @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "basetextextractform" }))
                   {
                @Html.ValidationSummary(false)
                @Html.HiddenFor(model => model.BaseTextModel.CorpusName, new { id = "corpusname" })
                <fieldset>
                    <legend>@PrismResources.Base_text_extract</legend>
                    <table>
                        <tr>
                            <td valign="top">
                                <div class="editor-label">
                                    @Html.LabelFor(model => model.BaseTextModel.ExtractSegmentID)
                                </div>
                                <div class="editor-field">
                                    @Html.DropDownListFor(model => model.BaseTextModel.ExtractSegmentID, (System.Collections.Generic.IEnumerable<SelectListItem>)ViewData["BaseTextTOCSegments"])
                                    @Html.ValidationMessageFor(model => model.BaseTextModel.ExtractSegmentID)
                                </div>
                                <br />
                        <input type="button" value="View" id="basetextviewbutton" />

                            </td>
                            <td valign="top">
                                <div class="editor-label">
                                    @PrismResources.Segment_filter
                                </div>
                                Content behaviour: @Html.EnumDropDownListFor(Model => Model.BaseTextModel.ContentBehaviour)

                                <table id="basetextattribfiltertable">
                                    <thead>
                                        <tr>
                                            <th>
                                                <span class="editor-label">@PrismResources.Name_ie_name_of_attrib</span>
                                            </th>
                                            <th>
                                                <span class="editor-label">@PrismResources.Value_ie_value_of_attrib</span>
                                            </th>
                                            <th>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model.BaseTextModel.AttributeFilters != null && Model.BaseTextModel.AttributeFilters.Length > 0)
                                        {
                                            for (int i = 0; i < Model.BaseTextModel.AttributeFilters.Length; i++)
                                            {
                                                string indexval = i.ToString();
                                                string rowid = "basetextattribfilterrow-" + indexval;
                                                string rowhtml = Prism.Controllers.CorpusController.AttributeRowHtml("BaseTextModel.AttributeFilters", Model.BaseTextModel.CorpusName, i, Model.BaseTextModel.AttributeFilters[i].Name, Model.BaseTextModel.AttributeFilters[i].Value, false);
                                                <tr id='Tr1'>
                                                    @rowhtml
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                                <br />
                                <input type="button" value="Add" id="addbasetextfilterattrib" />
                            </td>
                            <td>
                                <p>
                                    @Html.LabelFor(model => model.BaseTextModel.AuthorTranslator):
                                    @Model.BaseTextModel.AuthorTranslator<br />
                                    @Html.LabelFor(model => model.BaseTextModel.Genre):
                                    @Model.BaseTextModel.Genre<br />
                                    @Html.LabelFor(model => model.BaseTextModel.CopyrightInfo):
                                    @Model.BaseTextModel.CopyrightInfo<br />
                                    @Html.LabelFor(model => model.BaseTextModel.ReferenceDate):
                                    @Model.BaseTextModel.ReferenceDate<br />
                                    @Html.LabelFor(model => model.BaseTextModel.SegmentCount):
                                    @Model.BaseTextModel.SegmentCount<br />
                                </p>
                            </td>
                        </tr>
                    </table>
                    <input type="hidden" id="nextbasetextattribfilterrowindex" value="@ViewData["nextbasetextattribfilterrowindex"]" />

                </fieldset>
                }
            </td>
            <td valign="top" style="width:50%">
                @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "versionextractform" }))
                   {
                @Html.ValidationSummary(false)
                @Html.HiddenFor(model => model.VersionModel.CorpusName, new { id = "corpusname" })
                @Html.HiddenFor(model => model.VersionModel.NameIfVersion, new { id = "versionname" })
                <fieldset>
                    <legend>Version extract</legend>
                    <table>
                        <tr>
                            <td valign="top">
                                <div class="editor-label">
                                    @Html.LabelFor(model => model.VersionModel.ExtractSegmentID)
                                </div>
                                <div class="editor-field">
                                    @Html.DropDownListFor(model => model.VersionModel.ExtractSegmentID, (System.Collections.Generic.IEnumerable<SelectListItem>)ViewData["VersionTOCSegments"])
                                    @Html.ValidationMessageFor(model => model.VersionModel.ExtractSegmentID)
                                </div>
                                <br />
                        <input type="button" value="View" id="versionviewbutton" />

                            </td>

                            <td valign="top">
                                <div class="editor-label">
                                    @PrismResources.Segment_filter
                                </div>
                                Content behaviour: @Html.EnumDropDownListFor(Model => Model.VersionModel.ContentBehaviour)

                                <table id="versionattribfiltertable">
                                    <thead>
                                        <tr>
                                            <th>
                                                <span class="editor-label">@PrismResources.Name_ie_name_of_attrib</span>
                                            </th>
                                            <th>
                                                <span class="editor-label">@PrismResources.Value_ie_value_of_attrib</span>
                                            </th>
                                            <th>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model.VersionModel.AttributeFilters != null && Model.VersionModel.AttributeFilters.Length > 0)
                                        {
                                            for (int i = 0; i < Model.VersionModel.AttributeFilters.Length; i++)
                                            {
                                                string indexval = i.ToString();
                                                string rowid = "versionattribfilterrow-" + indexval;
                                                string rowhtml = Prism.Controllers.CorpusController.AttributeRowHtml("VersionModel.AttributeFilters", Model.VersionModel.CorpusName, i, Model.VersionModel.AttributeFilters[i].Name, Model.VersionModel.AttributeFilters[i].Value, false);
                                                <tr id='@rowid'>
                                                    @rowhtml
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                                <br />
                                <input type="button" value="Add" id="addversionfilterattrib" />
                            </td>
                            <td>
                                <p>
                                    @Html.LabelFor(model => model.VersionModel.AuthorTranslator):
                                    @Model.VersionModel.AuthorTranslator<br />
                                    @Html.LabelFor(model => model.VersionModel.Genre):
                                    @Model.VersionModel.Genre<br />
                                    @Html.LabelFor(model => model.VersionModel.CopyrightInfo):
                                    @Model.VersionModel.CopyrightInfo<br />
                                    @Html.LabelFor(model => model.VersionModel.ReferenceDate):
                                    @Model.VersionModel.ReferenceDate<br />
                                    @Html.LabelFor(model => model.VersionModel.SegmentCount):
                                    @Model.VersionModel.SegmentCount<br />
                                </p>
                            </td>
                        </tr>
                    </table>
                    <input type="hidden" id="nextversionattribfilterrowindex" value="@ViewData["nextversionattribfilterrowindex"]" />
                </fieldset>
                }
            </td>
            
        </tr>
    </table>
    <div  style="position: relative; width: 100%">
        <table class="noborders" style="width: 100%; ">
            <tr>
                <td valign="top">
                    <div>
                        <div id="basetextenclosurediv">
                            <textarea id="basetexteditor" name="basetexteditor"></textarea>
                        </div>
                    </div>
                </td>
                <td valign="top" style="text-align:center">

                    <input type="button" id="align" value="Align" /><br />
                    <input type="button" id="editalign" value="Edit" /><br />
                    <input type="button" id="confirmalign" value="Confirm" /><br />
                    <input type="button" id="confirmall" value="Confirm all" /><br />
                    <input type="button" id="removealign" value="Remove" /><br />
                    <input type="button" id="removedraft" value="Remove draft" /><br />
                    <input type="button" id="removeallalign" value="Remove all" /><br />
                    <input type="button" id="autoalign" value="Auto" /><br />
                    <input type="button" class="btn" id="moorealigner" value="Auto (Moore)" /><br />

                </td>
                <td valign="top">
                    <div>
                        <div id="versionenclosurediv">
                            <textarea id="versioneditor" name="versioneditor"></textarea>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
        <div id="graphics"  style="position: absolute;top: 40px; left: 0; width: 100%; height:100%;
            overflow: hidden; pointer-events: none">
        </div>

    </div>
    <div>
        @Html.ActionLink(PrismResources.Back_to_corpus, "Index", "Corpus", new { CorpusName = Model.BaseTextModel.CorpusName }, null)
    </div>

@section HeadContent
{

<script src="@Url.Content("~/Scripts/Prism-Formatting.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Prism-Utils.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Prism-Editor.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Prism-Aligner.js")" type="text/javascript"></script>
<script src="@Url.Content("~/ckeditor/ckeditor.js")" type="text/javascript"></script>
<script src="@Url.Content("~/ckeditor/adapters/jquery.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Content/TaggingStyles.css")" rel="stylesheet" type="text/css" />
<link id="markercss" href="@Url.Content("~/Content/EditorSegmentMarkers.css")" rel="stylesheet" type="text/css" />
<link id="corpuscss" href="@Url.Content("~/Corpus/CorpusCss?CorpusName=" + Model.BaseTextModel.CorpusName)" rel="stylesheet" type="text/css" />

<script src="@Url.Content("~/Scripts/jsDraw2D_Uncompressed.js")" type="text/javascript"></script>

}

Prism/Views/Aligner/SegStats.cshtml
<div id="vivtestdiv">
<table id='vivtesttable' class='sortable'>
@Html.Raw(ViewData["tablecontent"].ToString());

</table>
@Html.ActionLink("Download XML", "SegStatsDownload", new {CorpusName = ViewData["corpusname"], baseTextSegmentID = ViewData["segid"]})
</div>

<script type="text/javascript"  >
    //alert('aha');

    $(function () {

        //alert('aha2');
        sorttable.forceinit($('#vivtesttable')[0]);
        //sorttable.forceinit($('#vivtesttable2')[0]);
        //alert('aha3');

    });


</script>

Prism/Views/Aligner/Test.cshtml
@{ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage<dynamic>" }

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
    Test
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div id="testdiv" style="height: 300px; z-index: 2">
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" style="position: absolute;
        top: 0; left: 0;">
   <line id="myline" x1="0" y1="0" x2="200" y2="200"
   style="stroke:rgb(255,0,0);stroke-width:2"/>
 </svg>
    <div style="position: relative">
        <table >
            <tr valign="top">
                <td>
                    <iframe id="leftiframe">
                        @{ --                    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >
                    <html xmlns="http://www.w3.org/1999/xhtml">
                    <head>
                    </head>
                    <body>
                    </body>
                    </html>
                        --}

                    </iframe>
                </td>
                <td>
                    Buttons go here<br />
                    <input id="test" type="button" value="Test" />
                </td>
                <td>
                    <iframe id="rightiframe">
                        @{ --                    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >
                    <html xmlns="http://www.w3.org/1999/xhtml">
                    <head>
                    </head>
                    <body>
                    </body>
                    </html>
                        --}

                    </iframe>
                </td>
            </tr>
        </table>
        <div id="svgbasics" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;
            overflow: hidden">
        </div>
    </div>
    <div id="leftdiv" style="height: 200px; overflow: auto;">
        Here's some longer text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        <span id="plumbleft">linked</span><br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
    </div>
    <div id="rightdiv" style="height: 200px; overflow: auto">
        Here's some longer text<br />
        Here's some text<br />
        Here's some text<br />
        <span id="plumbright">linked</span><br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
        Here's some text<br />
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="HeadContent" runat="server">
    <style type="text/css">
        
    </style>
    <script src="@Url.Content("~/Scripts/Prism-Test.js")" type="text/javascript"></script>
@{ --    <script src="@Url.Content("~/Scripts/jquery.svg/jquery.svg.js")" type="text/javascript"></script>
--}
   

@{ -- <script src="@Url.Content("~/Scripts/wz_jsgraphics.js")" type="text/javascript"></script>
--}


  <script src="@Url.Content("~/Scripts/jsDraw2D_Uncompressed.js")" type="text/javascript"></script>


    
</asp:Content>