Prism/Controllers/VisualiseController.cs
/*
    Version Variation Visualisation (VVV)
    http://www.delightedbeauty.org
    
    Copyright (c) Kevin Flanagan, 2012.
    http://www.kftrans.co.uk
  
    This file is part of VVV.

    VVV is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    VVV is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with VVV.  If not, see <http://www.gnu.org/licenses/>.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EblaAPI;
using EblaImpl;
using Prism.Models;

namespace Prism.Controllers
{
    [Authorize]
    public class VisualiseController : PrismController
    {

        [HttpGet]
        public ActionResult FindSegments(string CorpusName)
        {
            var m = new FindSegmentModel();
            var items = new List<SelectListItem>();

            var versions = CorpusController.GetActiveCorpusSelection();

            items.Add(new SelectListItem() { Text = "[all]", Value = string.Empty });
            foreach (var v in versions)
                items.Add(new SelectListItem() { Text = v, Value = v });

            ViewData["versionlist"] = items;
            var basetext = PrismHelpers.GetBaseText(CorpusName);
            ViewData["TOCSegments"] = DocumentController.ConstructContentList(basetext);
            return PartialView("FindSegmentDialog", m);
        }

        bool WithinLimits(double floor, double ceiling, double value)
        {
            if (floor >= 0)
                if (value < floor)
                    return false;
            if (ceiling >= 0)
                if (value > ceiling)
                    return false;
            return true;
        }

        [HttpPost]
        public ActionResult GetFindSegmentsData(string CorpusName, string SearchText, bool SearchBaseText, bool SearchVersion, string VersionName,
            double VivFloor, double VivCeiling, double EddyFloor, double EddyCeiling, int metricTypeVal, AttributeModel[] AttributeFilters, int WithinSegmentID, SegmentContentBehaviour ContentBehaviour)
        {
            try
            {
                if (!Enum.IsDefined(typeof(VariationMetricTypes), metricTypeVal))
                    throw new Exception(PrismResources.Unrecognised_metric_type_value + metricTypeVal.ToString());

                VariationMetricTypes metricType = (VariationMetricTypes)metricTypeVal;

                if (SearchBaseText && SearchVersion)
                    throw new Exception("UI error - SearchBaseText && SearchVersion is true");
                SearchText = SearchText.Trim();
                //if (SearchText.Length < 3)
                //    throw new Exception("Search text must be at least three characters");

                //var corpus = PrismHelpers.GetCorpus(CorpusName);
                var baseText = PrismHelpers.GetBaseText(CorpusName);
                var corpus = PrismHelpers.GetCorpus(CorpusName);

                int startPosForSearch = 0;
                int lengthForSearch = baseText.Length();
                if (WithinSegmentID != -1)
                {
                    var withinSeg = baseText.GetSegmentDefinition(WithinSegmentID);
                    if (withinSeg == null)
                        throw new Exception("Unable to retrieve 'within' segment with ID " +WithinSegmentID.ToString() );

                    startPosForSearch = withinSeg.StartPosition;
                    lengthForSearch = withinSeg.Length;
                }


                var sb = new System.Text.StringBuilder();

                var versionDocs = new Dictionary<string, IDocument>();
                var alsets = new Dictionary<string, IAlignmentSet>();
                var alignmentMaps = new Dictionary<string, Dictionary<int, SegmentAlignment>>();
                var versions = CorpusController.GetActiveCorpusSelection();
                MultipleSegmentVariationData data = null;
                HashSet<int> segIdsWithinLimits = null;
                // TODO - optimise this by adding arg to RetrieveMultipleSegmentVariationData that specifies the segs
                // required, then perform other filtering first to obtain that arg, particular w.r.t. WithinSegmentID?
                if (VivFloor >= 0 || VivCeiling >= 0 || EddyFloor >= 0 || EddyCeiling >= 0)
                {
                    if (VivFloor >= 0 && VivCeiling >= 0)
                        if (VivFloor > VivCeiling)
                            throw new Exception("Floor value must not be greater than ceiling value");
                    if (EddyFloor >= 0 && EddyCeiling >= 0)
                        if (EddyFloor > EddyCeiling)
                            throw new Exception("Floor value must not be greater than ceiling value");

                    data = corpus.RetrieveMultipleSegmentVariationData(null, null, metricType, versions, false);

                    segIdsWithinLimits = new HashSet<int>();

                    int versionIndexStart = 0;
                    int versionIndexEnd = data.VersionNames.Length - 1;
                    if (false)//!string.IsNullOrEmpty(VersionName))
                    {
                        versionIndexStart = new List<string>(data.VersionNames).IndexOf(VersionName);
                        versionIndexEnd = versionIndexStart;
                    }

                    for (int i = 0; i < data.BaseTextSegmentIDs.Length; i++)
                    {
                        if (!WithinLimits(VivFloor, VivCeiling, data.VivValues[i]))
                            continue;

                        if (EddyFloor >= 0 || EddyCeiling >= 0)
                        {
                            bool skip = true;
                            for (int vindex = versionIndexStart; vindex <= versionIndexEnd; vindex++)
                                if (WithinLimits(EddyFloor, EddyCeiling, data.EddyValues[vindex][i]))
                                {
                                    skip = false;
                                    break;
                                }
                            if (skip)
                                continue;
                        }
                        segIdsWithinLimits.Add(data.BaseTextSegmentIDs[i]);

                    } // for (all base text segs)

                } // if (variation criteria set)

                if (SearchVersion)
                {
                    if (!string.IsNullOrEmpty(VersionName))
                    {
                        //versionDocs.Add(PrismHelpers.GetVersion(CorpusName, VersionName));
                        //alsets.Add(PrismHelpers.GetAlignmentSet(CorpusName, VersionName));
                        versions.Clear();
                        versions.Add(VersionName);
                    }
                    //else
                    GetVersionsData(baseText, versions, CorpusName, versionDocs, alsets, alignmentMaps);

                    //{
                        
                    //    foreach (var v in versions)
                    //    {
                    //        var d = PrismHelpers.GetVersion(CorpusName, v);
                    //        versionDocs.Add(d);
                    //        var alset = PrismHelpers.GetAlignmentSet(CorpusName, v);
                    //        alsets.Add(alset);
                    //        var l = new List<SegmentAlignment>();
                    //        l.AddRange(alset.FindAlignments(null, null, 0, baseText.Length(), 0, d.Length()));
                    //        var m = new Dictionary<int, SegmentAlignment>();
                    //        foreach (var al in l)
                    //        {
                    //            if (al.SegmentIDsInBaseText.Length == 1)
                    //            {
                    //                m.Add(al.SegmentIDsInBaseText[0], al);
                    //            }
                    //        }
                    //        alignmentMaps.Add(m);
                    //    }
                    //}
                }

                var attribFilter = DocumentController.EblaAttribsFromModel(AttributeFilters);
                var cbFilter = new List<SegmentContentBehaviour>() { ContentBehaviour };
                var segs = baseText.FindSegmentDefinitions(startPosForSearch, lengthForSearch, false, false, attribFilter.ToArray(), cbFilter.ToArray());
                foreach (var seg in segs)
                {
                    if (seg.Length < 1 || seg.Length > 3000)
                        continue;

                    if (segIdsWithinLimits != null)
                        if (!segIdsWithinLimits.Contains(seg.ID))
                            continue;

                    bool includeSegment = true;
                    var segText = baseText.GetDocumentContentText(seg.StartPosition, seg.Length);

                    if (!string.IsNullOrEmpty(SearchText))
                    {
                        if (SearchBaseText)
                        {
                            includeSegment &= segText.Contains(SearchText);
                        }
                        else
                        {
                            //if (versionDocs.Count == 1)
                            //{
                            //    segText = GetVersionContent(seg.ID, alsets[0], versionDocs[0]);
                            //    includeSegment &= (segText != null && segText.Contains(SearchText));
                                    
                            //}
                            //else
                            {

Prism/Views/Visualise/Alignments.cshtml
@model Prism.Models.CorpusModel

@section TitleContent
{
@ViewData["corpusname"]
    - @PrismResources.Alignment_view    
    }


	<div class="subnav subnav-fixed">
        <div class="container">
        	<div class="row title">
        		<div class="span12">
        			<h1>@ViewData["corpusname"] <small>@PrismResources.Alignment_view</small></h1>
        		</div>
        	</div>
	        <div class="row">
	            <div class="span6">
	                <h3><a href="#" class="tt" title="@PrismResources.Base_text_defn" rel="tooltip" data-placement="right">@PrismResources.Base_text <small>@ViewData["basetextdate"]</small></a></h3>
	            </div>
	            <div id="versionlist" class="span6">
	                <form class="form-horizontal pull-right">
	                <fieldset>
	                    <div class="control-group">
	                        <label class="control-label" for="versionlist">
	                            @PrismResources.Version</label>
	                        <div class="controls">
	                            @Html.Raw(ViewData["versionlist"].ToString())

	                        </div>
	                    </div>
	                </fieldset>
	                </form>
	            </div>
	        </div>
        </div>
    </div>
	
    <div class="container alignments withSubnav">
        <div class="row">
        	<div class="scroll-wrapper span4" style="height:400px;">
        		<div class="row scroll-content">
	                <div id="basetext" class="text no-select">
        				@Html.Raw(ViewData["basetextcontent"].ToString())

        			</div>
	            </div>
            </div>
        	<div class="scroll-wrapper span4" style="height:400px;">
        		<div class="row scroll-content">
	            	<div id="alignmentviz"></div>
	            </div>
            </div>
            <div class="scroll-wrapper span4" style="height:400px;">
        		<div class="row scroll-content">
	                <div id="versiontext" class="text no-select">
        			</div>
	            </div>
            </div>
        </div>
    </div>

    <input type="hidden" id="corpusname" value="@ViewData["corpusname"]" />
    <input type="hidden" id="selectedsegid" value="-1" />
    
@section HeadContent
{
<script src="@Url.Content("~/Scripts/Prism-Formatting.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Prism-Utils.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/vvv/d3/d3.v2.js")" type="text/javascript"></script>
@*<script src="@Url.Content("~/Scripts/d3/d3.js")" type="text/javascript"></script>*@
@*<script src="@Url.Content("~/Scripts/vvv/kinetic.js")" type="text/javascript"></script>*@
<script src="@Url.Content("~/Scripts/kinetic-v4.4.3.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/vvv/chroma/chroma.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/vvv/softdivscroll.js")" type="text/javascript"></script>
@*<script src="@Url.Content("~/Scripts/jquery.waypoints.min.js")" type="text/javascript"></script>*@
<script src="@Url.Content("~/Scripts/vvv/alignments/alignments.js")" type="text/javascript"></script>
<script src="http://use.typekit.com/oiq3xqg.js" type="text/javascript"></script>
<script type="text/javascript">        try { Typekit.load(); } catch (e) { }</script>
    
    }

@section HelpMenuItem
{
<a id="help-popover" href="#"><i class="icon-question-sign icon-white"></i> What&#8217;s this?</a>
<div id="help-content" style="display:none">
    <p>
        @Html.Raw(PrismResources.Alignment_view_help_html)
    </p>
</div>
    
    }

Prism/Views/Visualise/FindSegmentDialog.cshtml
@model Prism.Models.FindSegmentModel
<div  style="height: 500px" >

Find segments containing:
<input type="text" id="segmentsearchtext" />
<input type="button" id="findsegment" value="Find" /><br />
<input class="texttosearchradio" type="radio" name="texttosearch" id="segmentsearchbasetext"
    checked="checked" value="basetext" />In base text &nbsp;
<input class="texttosearchradio" type="radio" name="texttosearch" id="segmentsearchversion"
    value="version" />In version:
@Html.DropDownListFor(model => model.VersionToSearch, (System.Collections.Generic.IEnumerable<SelectListItem>)ViewData["versionlist"], new { id = "versiontosearch" })
<br />
Viv between
<input type="text" class="segmentsearchfloat" id="segmentsearchvivfloor" />
and
<input type="text" class="segmentsearchfloat" id="segmentsearchvivceiling" />, Eddy
between
<input type="text" class="segmentsearchfloat" id="segmentsearcheddyfloor" />
and
<input type="text" class="segmentsearchfloat" id="segmentsearcheddyceiling" />
<br />
<div style="width: 100%; border: 1px; border-color: Black; border-collapse:separate; border-style:solid">
Segment filter:<br/>
Content behaviour: @Html.EnumDropDownListFor(Model => Model.ContentBehaviour)

<table id="attribfiltertable" class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Value
            </th>
            <th>
            </th>
        </tr>
    </thead>
</table>
<input type="button" value="Add" id="addfilterattrib" />
</div>
Within: 
@Html.DropDownListFor(model => model.WithinSegmentID, (System.Collections.Generic.IEnumerable<SelectListItem>)ViewData["TOCSegments"])

<input type="hidden" id="nextattribfilterrowindex" value="1" />

<div id="findsegmentresults">
</div>
</div>
<script type="text/javascript">
    $(function () {

        $('#addfilterattrib').click(function (e) { PrismNS.FindSegmentDialog.AddFilterAttrib();  });


//        $('#findsegcheckall').click(function (e) { PrismNS.FindSegmentDialog.CheckAll();  });
  

        $('#findsegment').click(function (e) {PrismNS.FindSegmentDialog.Find();  });

    });


</script>

Prism/Views/Visualise/Index.cshtml
@*@{ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage<dynamic>" }*@

@section TitleContent
{
    @PrismResources.Parallel_view
}
    <div id="container"></div>
	<div class="container-fluid visualise">
    	<div id="panel">
    		<div class="row-fluid">
    			<div class="span6 title"><h3>Base Text <small>@ViewData["basetextdate"]</small></h3></div>
    			<div class="span6 title"><h3>@ViewData["versionname"] <small>@ViewData["versiondate"]</small></h3></div>
    		</div>
    		<div class="row-fluid">
    			<div id="basetextdiv" class="span6 version txt_0">
    				<div class="toolbar">
	    				<div class="toolHeader pull-right">
	    					<a href="#" class="tt" title="@PrismResources.Toggle_nav_tooltip" data-placement="right">
	    					<button type="button" class="hideFilter visible" id="hideFilter_0" onclick="showHideFilter(0);" ></button>
	    					</a>
	    				</div>
	    				
	    				<div class="tools">
						<p class="desc">@PrismResources.Filter_or_sort</p>
	    				</div>
	    			</div>
    				<div class="text nano">
	    				<div class="content">
	    					@Html.Raw(ViewData["basetextcontent"].ToString())

	    				</div>
    				</div>
    				<div class="connector" id="con_0"></div>
    			</div>
    			<div id="versiondiv" class="span6 version txt_1" data-versionname="@ViewData["versionname"]">
    				<div class="toolbar">
	    			   <div class="toolHeader pull-right">
	    			   		<a href="#" class="tt" title="Hide or reveal the vertical navigation tool" data-placement="right">
	    					<button type="button" class="hideFilter visible" id="hideFilter_1" onClick="showHideFilter(1);" ></button>
	    					</a>
	    				</div>
	    			    <div class="tools">
	    			    <p class="desc">@PrismResources.Filter_or_sort</p>
	    			    </div>
	    			</div>
    				<div class="text nano">
    					<div class="content">
    						@Html.Raw(ViewData["versioncontent"].ToString()))

    					</div>
    				</div>
    			
    			</div>
    		</div>
    	</div>
        <input type="hidden" id="corpusname" value="@ViewData["corpusname"]" />
        <input type="hidden" id="versionname" value="@ViewData["versionname"]" />
        <input type="hidden" id="selectedsegid" value="-1" />
    </div>

@section HeadContent
{
<script src="@Url.Content("~/Scripts/Prism-Formatting.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Prism-Utils.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/vvv/kinetic.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.scrollto.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.sb.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/vvv/nanoScroller/jquery.nanoscroller.js")" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/alignView/translation.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/alignView/nav.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/alignView/filter.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/alignView/connector.js")" type="text/javascript"></script>

<link href="@Url.Content("~/Content/css/alignView.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/css/nanoscroller.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/css/customselect.css")" rel="stylesheet" type="text/css" />

<script src="@Url.Content("~/Scripts/vvv/fruitmachine.js")" type="text/javascript"></script>
    }


@section HelpMenuItem
{
<a id="help-popover" href="#"><i class="icon-question-sign icon-white"></i> What&#8217;s this?</a>
<div id="help-content" style="display:none">
    <p>
        <i>Fruit Machine</i>: scroll the texts, click any segment (in Othello, here, a segment is a speech). Base Text and translation re-align automatically.<br /><br />
        <i>Barcode</i>: a bar represents a segment. Its size represents the word-count. The vertical navigation strip gives a text structure overview, and finds segments with defined features, using colours and shape to identify them.
    </p>
</div>

}

Prism/Views/Visualise/OthelloMap.cshtml
@*@{ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage<dynamic>" }*@


@section TitleContent
{
    Othello Corpus Map
    }
	<div class="subnav subnav-fixed">
        <div class="container">
        	<div class="row title">
        		<div class="span12">
        			<h1>@ViewData["corpusname"] <small>Map View</small></h1>
        		</div>
        	</div>
        </div>
    </div>
	
    <div class="container withSubnav map">
    	<div class="row">
    		<div class="span12">
    			<iframe frameborder="0" src="http://othellomap.s3-website-eu-west-1.amazonaws.com/embed.html" width="100%" height="100%"></iframe>
    		</div>
    	</div>
    </div>

<asp:Content ID="Content3" ContentPlaceHolderID="HeadContent" runat="server">
    <script src="@Url.Content("~/Scripts/Prism-Formatting.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/Prism-Utils.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.scrollto.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.sb.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/vvv/nanoScroller/jquery.nanoscroller.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/alignView/translation.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/alignView/nav.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/alignView/filter.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/alignView/connector.js")" type="text/javascript"></script>

    <link href="@Url.Content("~/Content/css/alignView.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/nanoscroller.css")" rel="stylesheet" type="text/css" />
 	<link href="@Url.Content("~/Content/css/customselect.css")" rel="stylesheet" type="text/css" />
 	
 	<!--[if IE]>
		<link rel="stylesheet" type="text/css" href="/Content/css/ie.css" />
	<![endif]-->


@section HelpMenuItem
    {
    <a id="help-popover" href="#"><i class="icon-question-sign icon-white"></i> What&#8217;s this?</a>
    <div id="help-content" style="display:none">
        <p>An interactive map showing locations for creations, editions and publishing in the Othello corpus that was collected during VVV phase 1 &amp; 2.</p>
    </div>

    }

Prism/Views/Visualise/SegmentVersionsTable.cshtml
@model Prism.Models.SegmentVersionsTableModel


@section HeadContent
{
    <script src="@Url.Content("~/Scripts/vvv/d3/d3.v2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/vvv/chroma/chroma.js")" type="text/javascript"></script>
    <script type="text/javascript" src="~/Scripts/i18n/grid.locale-en.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.jqGrid.js"></script>

    <script src="@Url.Content("~/Scripts/Prism-Utils.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Prism-SegmentVersionsTable.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Prism-FindSegmentDialog.js")" type="text/javascript"></script>
    @*<script src="@Url.Content("~/Scripts/jquery-ui-1.10.3.custom.min.js")" type="text/javascript"></script>*@

    <link href="~/Content/jquery.jqGrid/ui.jqgrid-bootstrap.css" media="screen" type="text/css" rel="stylesheet" />

    @*<link href="@Url.Content("~/Content/css/ui-lightness/jquery-ui-1.10.3.custom.min.css")"
        rel="stylesheet" type="text/css" />*@
    <style type="text/css">
        /*.celltop 
        {
            position:absolute;
            top: 0px;
        }*/
        .cellbottom
        {
            position: absolute;
            bottom: 0px;
        }
        
        /* make jqgrid do word wrap on cells with long text */
        .ui-jqgrid tr.jqgrow td
        {
            word-wrap: break-word; /* IE 5.5+ and CSS3 */
            white-space: pre-wrap; /* CSS3 */
            white-space: -moz-pre-wrap; /* Mozilla, since 1999 */
            white-space: -pre-wrap; /* Opera 4-6 */
            white-space: -o-pre-wrap; /* Opera 7 */
            overflow: hidden;
            height: auto;
            vertical-align: top;
            padding-top: 3px;
            padding-bottom: 3px;
            position: relative;
        }
        
        /* make jqgrid do word wrap on headers with long text */
        th.ui-th-column div
        {
            white-space: normal !important;
            height: auto !important;
            padding: 2px;
        }
        
        .svdchart
        {
            width: 70px;
            height: 60px;
        }
        
        #modalContent input[type=text].segmentsearchfloat
        {
            width: 40px;
        }
    </style>
}
    <div style="height: 70px">
    </div>
    <div>
        @Html.HiddenFor(model => model.CorpusName, new { id = "corpusname" })
        <a href="@Url.Content("~/Home/Project#eddyviv")" class="tt" title="@PrismResources.Eddy_viv_desc_html"
            rel="tooltip" data-placement="right">@PrismResources.Variation_metric<i class="icon-question-sign"></i></a>
        <select id="variation-type-select">
            <!-- to be filled by JS -->
        </select>
        @PrismResources.Attribute:
        <select id="attribname">
            @foreach (var a in Model.AttribNames.Keys)
               {
            <option value="@Model.AttribNames[a]">
                @a</option>
            }
        </select>
        <input type="checkbox" id="showsvd" />@PrismResources.Show_svd_charts
        <br />
        <input type="button" value="@PrismResources.Add" id="addrows" title="@PrismResources.Table_search_add" />
        <input type="button" value="@PrismResources.Remove" id="deleterows" title="@PrismResources.Table_remove" />


        <div style="float: right;">
            @using (Html.BeginForm("ExportVersionsTable", "Visualise"))
               {
            <input type="hidden" name="CorpusName" id="submitcorpusname" />
            <input type="hidden" name="AttribName" id="submitattribname" />
            <input type="hidden" name="metricTypeVal" id="submitmetrictypeval" />
            <input type="submit" value="Export" />
            }
        </div>
        <input type="checkbox" checked="checked" id="sizetowindow" />@PrismResources.Fit_grid_to_window
    </div>
    <table id="list2">
    </table>
    <div id="pager2">
    </div>

Prism/Views/Visualise/VivReportDialog.cshtml
@model EblaAPI.SegmentVariation

<div id="vivtestdiv">


<span class="display-label">Base text segment ID: </span><span class="display-field">
    @Model.BaseTextSegmentID.ToString()</span>
<span class="display-label">Viv value: </span><span class="display-field">
    @Model.VivValue.ToString()</span><br />

<span class="display-label">Segment content: </span><span class="display-field">
    @Model.BaseTextContent</span>
<br />
<br />
-- Eddy values (click column headers to sort)
<table id="vivtesttable" class="sortable" >
<thead>
<tr>
<th >
Version
</th>
<th>
Eddy value
</th>
<th>
Content
</th>
</tr>
</thead>
<tbody>
@for (int i = 0; i < Model.VersionSegmentVariations.Length; i++)
    {
<tr >
<td>
@Model.VersionSegmentVariations[i].VersionName
</td>
<td>
@Model.VersionSegmentVariations[i].EddyValue.ToString()
</td>
<td>
@Model.VersionSegmentVariations[i].VersionText
</td>

</tr>

     }
</tbody>
</table>

<br />
-- Tokens (click column headers to sort)
<table class="sortable" id="vivtesttable2">
<thead>
<tr >
<th>Token</th>
<th>Average count</th>
</tr>
</thead>
<tbody>
@for (int i = 0; i < Model.TokenInfo.Length; i++)
   {

   <tr >
   <td>@Model.TokenInfo[i].Token </td>
   <td>@Model.TokenInfo[i].AverageCount.ToString() </td>
   </tr>

   }
</tbody>
</table>
</div>
<script type="text/javascript"  >
    //alert('aha');

    $(function () {

        //alert('aha2');
        sorttable.forceinit($('#vivtesttable')[0]);
        sorttable.forceinit($('#vivtesttable2')[0]);
        //alert('aha3');

    });


</script>