Prism/Controllers/DocumentController.cs
//#define USE_OLD_UPLOAD
/*
    Version Variation Visualisation (VVV)
    http://www.delightedbeauty.org
    
    Copyright (c) Kevin Flanagan, 2012.
    http://www.kftrans.co.uk
  
    This file is part of VVV.

    VVV is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    VVV is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with VVV.  If not, see <http://www.gnu.org/licenses/>.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EblaAPI;
using EblaImpl;
using Prism.Models;
using EblaImpl.Extractor;
using System.IO;

namespace Prism.Controllers
{
    [Authorize]
    public class DocumentController : PrismController
    {
        #region Page rendering

        public ActionResult Index(string CorpusName, string NameIfVersion)
        {
            
            try
            {
                ViewData["extract"] = string.Empty;
                ViewData["nextattribfilterrowindex"] = (0).ToString();
                ViewData["extractindented"] = string.Empty;
                ICorpus corpus = PrismHelpers.GetCorpus(CorpusName);
                //EblaAPI.PredefinedSegmentAttribute[] atts = corpus.GetPredefinedSegmentAttributes();
                //ViewData["colourdata"] = GetColouringData(atts);
            
                IDocument doc = PrismHelpers.GetDocument(CorpusName, NameIfVersion);

                ViewData["TOCSegments"]= ConstructContentList( doc);

                DocumentExtractModel model = new DocumentExtractModel();
                //model.StartPos = 0;
                //model.Length = 500;
                //model.docModel = new DocumentModel();
                model.NameIfVersion = NameIfVersion;
                model.CorpusName = CorpusName;

                model.DocLength = doc.Length();
                DocumentMetadata meta = doc.GetMetadata();
                CorpusController.DocumentMetadataToModel(meta, model);

                return View(model);

            }
            catch (Exception ex)
            {
                string message = "An error occurred while trying to open the document: " + ex.Message;
                return RedirectToAction("Error", "Home", new { message = message });
            }
        }

		public ActionResult Info(string CorpusName, string NameIfVersion)
        {
            
            try
            {
                IDocument doc = PrismHelpers.GetDocument(CorpusName, NameIfVersion);
                DocumentMetadata meta = doc.GetMetadata();

                var m = new DocInfoViewModel();
                m.CorpusName = CorpusName;
                m.NameIfVersion = NameIfVersion;
                m.MetaData = meta;

                return View(m);

            }
            catch (Exception ex)
            {
                string message = "An error occurred while trying to open the document: " + ex.Message;
                return RedirectToAction("Error", "Home", new { message = message });
            }
        }

      
        public ActionResult Upload(string CorpusName, string NameIfVersion)
        {
            try
            {
                ICorpus corpus = PrismHelpers.GetCorpus(CorpusName);
                HtmlUploadModel model = new HtmlUploadModel();
                model.CorpusName = CorpusName;
                model.NameIfVersion = NameIfVersion;
                model.encoding = PrismEncoding.UTF8;
                return View(model);

            }
            catch (Exception ex)
            {
                string message = string.Empty;
                message = "An error occurred while trying to open corpus '" + CorpusName + "': " + ex.Message;
                return RedirectToAction("Error", "Home", new { message = message });
            }

        }

        public ActionResult BaseUpload(string corpusName, string uploadType)
        {
            try
            {
                if (string.IsNullOrEmpty(corpusName) || corpusName == "undefined")
                    throw new Exception("Corpus Name was not informed.");

                var model = new UploadFilesResult
                {
                    CorpusName = corpusName,
                    UploadType = uploadType
                };

                ViewData["CorpusName"] = corpusName;
                
                return View(model);
            }
            catch (Exception ex)
            {
                var message = "An error occurred while trying to open UploadFilesResult : " + ex.Message;
                return RedirectToAction("Error", "Home", new { message = message });
            }
        }

        public ActionResult VersionUpload(string corpusName, string uploadType)
        {
            try
            {
                var model = new UploadFilesResult
                {
                    CorpusName = corpusName,
                    UploadType = uploadType
                };
                return View(model);
            }
            catch (Exception ex)
            {
                var message = "An error occurred while trying to open UploadFilesResult : " + ex.Message;
                return RedirectToAction("Error", "Home", new { message = message });
            }
        }

        [System.Web.Mvc.ValidateInput(false)]
        public ActionResult UploadContent(HtmlUploadContentModel model)
        {
            try
            {
                HtmlErrors errors = null;
                string htmlDoc = HtmlContentToHtmlDoc(model.HtmlContent);
                if (string.IsNullOrWhiteSpace(model.NameIfVersion))
                {
                    errors = PrismHelpers.GetCorpus(model.CorpusName).UploadBaseText(htmlDoc);
                }
                else
                {
                    errors = PrismHelpers.GetCorpus(model.CorpusName).UploadVersion(model.NameIfVersion, htmlDoc);
                }

                if (errors.HtmlParseErrors.Length > 0)
                {
                    string msg =  PrismResources.Upload_Error_Parsing_Html;

                    foreach (var e in errors.HtmlParseErrors)
                    {
                        string message = e.Reason + " at line " + e.Line.ToString() + ", position " + e.LinePosition.ToString();
                        msg += message + "\n";
                    }

                    throw new Exception(msg);

                }

                var results = new ResultModel {Succeeded = true};
                return MonoWorkaroundJson(results);
            }
            catch (Exception ex)
            {
                return MonoWorkaroundJson(new ResultModel { Succeeded = false, ErrorMsg = System.Net.WebUtility.HtmlEncode(ex.Message) });
            }
        }

        [System.Web.Mvc.ValidateInput(false)]
        [HttpPost]
        public JsonResult UploadFiles()
        {
            try
            {               
                var r = new List<UploadFilesResult>();
                ViewBag.Message = string.Empty;

                if (ViewBag.BaseFiles == null)
                    ViewBag.BaseFiles = 0;
                if (ViewBag.VersionFiles == null)
                    ViewBag.VersionFiles = 0;
                string message;
                var model = new HtmlUploadModel
                {
                    UploadType = Request.Form["uploadType"],
                    CorpusName = Request.Form["corpusName"]
                };

                if (string.IsNullOrEmpty(model.CorpusName) || model.CorpusName == "undefined")
                {
                    message = "You need to create a corpus first.";
                    ModelState.AddModelError("CorpusName", message);
                    AddDangerAlert(string.Format("An error occurred: {0}.", message));
                    ViewBag.Message = message;
                    return Json(message);
                }

                if (ModelState.IsValid)
                {
                    foreach (string baseFile in Request.Files)
                    {
                        if (model.UploadType == "base")
                            ViewBag.BaseFiles += 1;

                        if (model.UploadType == "version")
                            ViewBag.VersionFiles += 1;

                        var uploadedFile = Request.Files[baseFile];
                        var uploadedFiles = UploadFiles(model, uploadedFile);
                        r.AddRange(uploadedFiles);
                    }

                    return Json(GetFileList(r));
                }
                else
                {
                    message = "An error occurred: The information is not valid.";
                    AddDangerAlert(message);
                    ViewBag.Message = message;
                    ModelState.AddModelError(string.Empty, message);
                    return Json(string.Empty, message);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = string.Format("An error occurred: {0}.", ex.Message);
                AddDangerAlert(string.Format("An error occurred: {0}.", ex.Message));                
                throw ex;
            }
        }

        public List<UploadFilesResult> UploadFiles(HtmlUploadModel model, HttpPostedFileBase file)
        {
            var r = new List<UploadFilesResult>();
            try
            {
                if (file == null || file.ContentLength == 0)
                {
                    throw new Exception(PrismResources.Upload_Select_File);
                }

Prism/Views/Document/AutoSegmentDialog.cshtml
@model Prism.Models.AutoSegmentationModel

<div>
    @Html.HiddenFor(x => x.CorpusName)
    @Html.HiddenFor(x => x.VersionName)
    <br />
    @PrismResources.Auto_segment_descrip<br /><br />
    <asp:Panel   ID="Panel1" runat="server" GroupingText="@PrismResources.Tag_based">
    <input name="Option" id="Radio1" type="radio" value="around" checked="checked" />@PrismResources.Segment_around_tag_pair<br />
    <input name="Option" id="Radio2" type="radio" value="after" />@PrismResources.Segment_after_tag<br />
    <input name="Option" id="Radio3" type="radio" value="play1" />@PrismResources.Play_format_1<br />
        @PrismResources.Tag: 
    <input id="Tag" name="Tag" type="text" value="p" /><br />
    </asp:Panel>
    <br />
    <input name="Option" id="Option" type="radio" value="" disabled="disabled" />@PrismResources.Segment_on_punc<br />



</div>

Prism/Views/Document/BaseUpload.cshtml
@model Prism.Models.UploadFilesResult

@using Prism.HtmlHelpers

@section TitleContent
{
    VVV - @PrismResources.Upload_doc
}


@section HeadContent
{
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.bootstrap.wizard.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.iframe-transport.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.fileupload.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.fileupload-jquery-ui.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.fileupload-process.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.fileupload-validate.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/Prism-NewUpload.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>

    <link href="@Url.Content("~/Content/font-awesome.min.css")" rel="stylesheet" type="text/css"/>
    <link href="@Url.Content("~/Content/bootstrap-theme.min.css")" rel="stylesheet" type="text/css"/>
    <link href="@Url.Content("~/Content/css/wizard.css")" rel="stylesheet" type="text/css"/>
    <link href="@Url.Content("~/Content/newer/css/jquery.fileupload.css")" rel="stylesheet" type="text/css"/>
}


<div class="container">
    <div class="page-header">
        @using (Html.BeginForm("UploadFiles", "Document", FormMethod.Post, new { id = "UploadBaseForm" }))
        {
            <h2>
                @Model.CorpusName: @PrismResources.Base_text - @PrismResources.Upload_doc
            </h2>
            @Html.Raw(PrismResources.Upload_doc_guidance)

            @Html.HiddenFor(model => model.CorpusName, new { id = "CorpusName" })

            <div class="well dashedzone" style="margin-right: 10px;">
                <div class="span10">
                    <h3 class="info-text">Drop your file here</h3>
                    <p class="category">or click "Add new" to select your base text</p>
                </div>
                <div class="control-group span10">
                    <div class="controls">
                        <div id="dropzonebase" class="dropzone"></div>

                        <span class="btn btn-primary fileinput-button">
                            <i class="fa fa-plus"></i>
                            <span>@PrismResources.Add_new</span>
                            <input id="baseFileUpload" class="fileupload" type="file" name="base[]" />
                            @*<input type="hidden" name="CorpusName" value="@ViewData["CorpusName"]">*@
                        </span> or drop your file here.

                        <br>
                        <br>

                        <!-- Progress bar -->
                        <div id="baseProgress" class="progress">
                            <div id="baseProgressBar" class="progress-bar progress-bar-info"></div>
                        </div>
                        <!-- Uploaded files -->
                        <div id="baseFiles" class="files"></div>

                        <div id="baseFilesUploaded"></div>
                    </div>
                </div>
            </div>
        }
        

        
    </div>
    @Html.ValidationSummary(true)

</div>
    

Prism/Views/Document/Index.cshtml
@model Prism.Models.DocumentExtractModel

@section HeadContent {
<script src="@Url.Content("~/Scripts/Prism-Formatting.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Prism-Utils.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Prism-Editor.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Prism-Document.js")" type="text/javascript"></script>
<script src="@Url.Content("~/ckeditor/ckeditor.js")" type="text/javascript"></script>
<script src="@Url.Content("~/ckeditor/adapters/jquery.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Content/TaggingStyles.css")" rel="stylesheet" type="text/css" />
<link id="markercss" href="@Url.Content("~/Content/EditorSegmentMarkers.css")" rel="stylesheet" type="text/css" />
<link id="corpuscss" href="@Url.Content("~/Corpus/CorpusCss?CorpusName=" + Model.CorpusName)" rel="stylesheet" type="text/css" />
<link href="@Url.Content(" ~/Content/bootstrap/css/bootstrap.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content(" ~/Content/css/style.css")" rel="stylesheet" type="text/css" />
    }

@section TitleContent
{
        VVV - @Model.CorpusName:
        @if (string.IsNullOrEmpty(Model.NameIfVersion))
        {
            @PrismResources.Base_text
        }
        else
        {
            @("'" + Model.NameIfVersion + "'")
        }
    }



	<div class="container">
		<div class="page-header">
			<div class="row">
				<div class="span9">
				    <h2>
				        @Model.CorpusName:
				        @if (string.IsNullOrEmpty(Model.NameIfVersion))
				        {
				            @PrismResources.Base_text
				        }
				        else
				        {
				            @Model.NameIfVersion
				        }
						<small> @Model.ReferenceDate</small>
					</h2>
					<p>
						<strong>@Html.NameFor(model =>model.Description):</strong> @Model.Description
					</p>
				</div>
				<div class="span3">
					<p>
						<strong>@Html.NameFor(x =>x.AuthorTranslator):</strong> @Model.AuthorTranslator
					</p>
					<p>
						<strong>@Html.NameFor(x => x.CopyrightInfo):</strong> @Model.CopyrightInfo
					</p>
					<p>
						<strong>@Html.NameFor(x => x.DocLength):</strong> @Model.DocLength
					</p>	
					<p>

					</p>
				</div>
			</div>
		</div>
	    <div class="row">
			<div class="span12">
				<div class="well">
					@using (Html.BeginForm( null, null, FormMethod.Post, new { id="docextractform", @class="form-horizontal" }))
					{
					@Html.ValidationSummary(false)
				    @Html.HiddenFor(model => model.CorpusName, new { id = "corpusname" })
					@Html.HiddenFor(model => model.NameIfVersion, new { id = "versionname" })
					@Html.HiddenFor(model => model.DocLength)
					<div class="pull-right">
						<input type="button" value="@PrismResources.View_ie_buttonaction" id="viewbutton" />
					</div>
					<fieldset>
						<legend>
							@PrismResources.View_extract
						</legend>
						<div class="control-group">
							<label class="control-label" for="">@PrismResources.Extract_to_show</label>
							<div class="controls">
								@Html.DropDownListFor(model => model.ExtractSegmentID, (System.Collections.Generic.IEnumerable<SelectListItem>)ViewData["TOCSegments"])
				                @Html.ValidationMessageFor(model => model.ExtractSegmentID)
							</div>
						</div>
					
						<div class="control-group">
							<label class="control-label">@PrismResources.Segment_filter<a href="#" class="tt" title="@PrismResources.Seg_filter_tooltip" rel="tooltip" data-placement="right"><i class="icon-question-sign"></i></a></label>
							<div class="controls">
                                Content behaviour: @Html.EnumDropDownListFor(Model => Model.ContentBehaviour)
								<table id="attribfiltertable" class="table">
	                                <thead>
	                                    <tr>
	                                        <th>
	                                            @PrismResources.Name_ie_name_of_attrib
	                                        </th>
	                                        <th>
	                                            @PrismResources.Value_ie_value_of_attrib
	                                        </th>
	                                        <th>
	                                        </th>
	                                    </tr>
	                                </thead>
	                                <tbody>
										@if (Model.AttributeFilters != null && Model.AttributeFilters.Length > 0)
                                        { 
                                            for (int i = 0; i < Model.AttributeFilters.Length; i++)
				                            {
											    string indexval = i.ToString();
											    string rowid = "attribfilterrow-" + indexval;
											    string rowhtml = Prism.Controllers.CorpusController.AttributeRowHtml("AttributeFilters", Model.CorpusName, i, Model.AttributeFilters[i].Name, Model.AttributeFilters[i].Value, false);
											    <tr id='@rowid'>
											    @rowhtml
											    </tr>
										    }
                                        }

									</tbody>
								</table>
								<input type="button" value="@PrismResources.Add" id="addfilterattrib" />
							</div>
						</div>
		
			        	<input type="hidden" id="nextattribfilterrowindex" value="@ViewData["nextattribfilterrowindex"]" />

					</fieldset>
					}
				</div>

			    <div>
			        <div id="editorenclosurediv">
			            <textarea id="doceditor" name="doceditor">
			        @Html.Raw(ViewData["extract"].ToString());
	        
			        
			        </textarea>
			        </div>
			    </div>
			    <div>

                    <input id="autoseg" type="button" class="btn btn-primary" value="@PrismResources.Auto_segment..." /> <br />
			    </div>

			</div>
		</div>
	</div>

Prism/Views/Document/Info.cshtml
@model Prism.Models.DocInfoViewModel


@section TitleContent
{
    VVV - @ViewData["VersionName"]
    }


	<div class="container">
		<header>
			<h1>@Model.NameIfVersion<small>@Model.MetaData.ReferenceDate</small></h1>
			<p>@PrismResources.Corpus_name: @Model.CorpusName</p>
		</header>
		<section id="description">
			<div class="row">
				<div class="span5">
					<dl>
						<dt>@Html.NameFor(x=>x.MetaData.Description)</dt>
						<dd>@Model.MetaData.Description</dd>
					</dl>
				</div>
				<div class="span7">
					<dl>
						<dt>@Html.NameFor(x => x.MetaData.LanguageCode)</dt>
  						<dd>@Model.MetaData.LanguageCode</dd>
  						
						<dt>@Html.NameFor(x => x.MetaData.ReferenceDate)</dt>
  						<dd>@Model.MetaData.ReferenceDate</dd>
  						
  						<dt>@Html.NameFor(x => x.MetaData.CopyrightInfo)</dt>
  						<dd>@Model.MetaData.CopyrightInfo</dd>
  						
  						<dt>@Html.NameFor(x => x.MetaData.Genre)</dt>
  						<dd>@Model.MetaData.Genre</dd>
  						
  						<dt>@Html.NameFor(x => x.MetaData.AuthorTranslator)</dt>
  						<dd>@Model.MetaData.AuthorTranslator</dd>
					</dl>
				</div>
			</div>
		</section>
		<section id="info">
			<div class="page-header">
				<h3>@PrismResources.Refs_and_info</h3>
			</div>
			
			<div class="row">
				<div class="span5">
					<p>@Model.MetaData.Information</p>
				</div>
			</div>
		</section>
	</div>

Prism/Views/Document/SegmentDefinitionDialog.cshtml
@model Prism.Models.SegmentDefinitionModel

@using Prism.HtmlHelpers
@Html.ValidationSummary(false)
<span class="display-label">Segment ID: </span><span class="display-field">
    @Model.ID.ToString()</span>
<span class="display-label">Segment start: </span><span class="display-field">
    @Model.startPos.ToString()</span>
<span class="display-label">Segment length: </span><span class="display-field">
    @Model.length.ToString()</span><br />
<span class="display-label">Segment content: </span><span class="display-field">
    @Model.Content</span>

    @Html.HiddenFor(x => x.startPos)
    @Html.HiddenFor(x => x.length)
    @Html.HiddenFor(x => x.CorpusName)
    @Html.HiddenFor(x => x.NameIfVersion)
    @Html.HiddenFor(x => x.ID)
<fieldset>
    Content behaviour: @Html.EnumDropDownListFor(model => model.ContentBehaviour)
    <legend>Attributes</legend>
    <table id="attribtable">
        <thead>
            <tr>
                <th>
                    <span class="editor-label">Name</span>
                </th>
                <th>
                    <span class="editor-label">Value</span>
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Attributes.Length; i++)
            {
                //EblaAPI.PredefinedSegmentAttribute pre = null;
                string indexval = i.ToString();
                string rowid = "attribrow-" + indexval;
                //string nameselectname = "Attributes[" + indexval + "].Name";
                //string valueinputname = "Attributes[" + indexval + "].Value";
                string rowhtml = Prism.Controllers.CorpusController.AttributeRowHtml("Attributes", Model.CorpusName, i, Model.Attributes[i].Name, Model.Attributes[i].Value, Model.ID == -1);
            <tr id='@rowid'>
                @Html.Raw(rowhtml)
            </tr>
            }
        </tbody>
    </table>
    <input type="button" value="Add" id="addattrib" />
</fieldset>
<input type="hidden" id="nextattribrowindex" value="@ViewData["nextattribrowindex"]" />
<script type="text/javascript">
    $(function () {

        $('#addattrib').click(function (e) { PrismNS.Utils.AddAttribRow('nextattribrowindex', 'Attributes', 'attribtable', 'attribrow-'); });
    });


</script>

Prism/Views/Document/Upload.cshtml
@model Prism.Models.HtmlUploadModel

@using Prism.HtmlHelpers

@section TitleContent
{
    VVV - @PrismResources.Upload_doc
}


@section HeadContent
{
    <script src="@Url.Content("~/ckeditor/ckeditor.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/ckeditor/adapters/jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Prism-Upload.js")" type="text/javascript"></script>
}


<div class="container">
    <div class="page-header">
        <h2>

            @Model.CorpusName:
            @if (string.IsNullOrEmpty(Model.NameIfVersion))
            {
                @PrismResources.Base_text
            }
            else
            {
                @Model.NameIfVersion
            }
            - @PrismResources.Upload_doc
        </h2>
    </div>
    <div class="well">
        @Html.Raw(PrismResources.Upload_doc_guidance)


    </div>
    <div class="alert-error">
        @Html.ValidationSummary(true)


    </div>
    <div class="well">
        <fieldset>
            <legend>@PrismResources.Paste_content</legend>
            <div id="editorenclosurediv">
                <textarea id="doceditor" name="doceditor">       </textarea>
            </div>
            <input type="button" class="btn-primary" value="@PrismResources.Upload_content" id="uploadcontent" />
        </fieldset>

    </div>

    <div class="well">


        @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(model => model.CorpusName, new { id = "uploadcorpusname" })
            @Html.HiddenFor(model => model.NameIfVersion, new { id = "uploadnameifversion" })
            <fieldset>
                <legend>Upload file</legend>
                <label for="file">
                    @PrismResources.Filename:
                </label>
                <input type="file" name="file" id="file" />
                @Html.EnumDropDownListFor(model => model.encoding)
                <p>
                    <input type="submit" class="btn-primary" value="@PrismResources.Upload_file" />
                </p>
            </fieldset>
        }
        @using (Html.BeginForm("Update", "Document", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(model => model.CorpusName, new { id = "updatecorpusname" })
            @Html.HiddenFor(model => model.NameIfVersion, new { id = "updatenameifversion" })
            <fieldset>
                <legend>@PrismResources.Update_file</legend>
                <label for="file">@PrismResources.Filename:</label>
                <input type="file" name="file" id="file1" />
                <p><input type="submit" class="btn-primary" value="@PrismResources.Update_file" /> </p>
            </fieldset>
        }

    </div>



</div>
    

Prism/Views/Document/VersionUpload.cshtml
@model Prism.Models.UploadFilesResult

@using Prism.HtmlHelpers

@section TitleContent
{
    VVV - @PrismResources.Upload_doc
}


@section HeadContent
{
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.bootstrap.wizard.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.iframe-transport.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.fileupload.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.fileupload-jquery-ui.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.fileupload-process.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.fileupload-validate.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/Prism-NewUpload.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>

    <link href="@Url.Content("~/Content/font-awesome.min.css")" rel="stylesheet" type="text/css"/>
    <link href="@Url.Content("~/Content/bootstrap-theme.min.css")" rel="stylesheet" type="text/css"/>
    <link href="@Url.Content("~/Content/css/wizard.css")" rel="stylesheet" type="text/css"/>
    <link href="@Url.Content("~/Content/newer/css/jquery.fileupload.css")" rel="stylesheet" type="text/css"/>
}


<div class="container">
    <div class="page-header">      
            @using (Html.BeginForm("UploadFiles", "Document", FormMethod.Post, new { id = "UploadVersionForm", enctype = "multipart/form-data" }))
            {
            <h2>
                @Model.CorpusName: @PrismResources.Version - @PrismResources.Upload_doc
            </h2>
            @Html.Raw(PrismResources.Upload_doc_guidance)

            @Html.HiddenFor(model => model.CorpusName, new { id = "CorpusName" })

            <div class="well dashedzone" style="margin-right: 10px;">
                <div class="span10">
                    <h3 class="info-text">Drop your file(s) here</h3>
                    <p class="category">or click "Add new" to select your version(s)</p>
                </div>
                <div class="control-group span10">
                    <div class="controls">
                        <div id="dropzoneversion" class="dropzone"></div>

                        <span class="btn btn-primary fileinput-button">
                            <i class="fa fa-plus"></i>
                            <span>@PrismResources.Add_new</span>
                            <input id="versionFileUpload" class="fileupload" type="file" name="versions[]" />
                        </span> or drop your file(s) here.

                        <br>
                        <br>

                        <!-- Progress bar -->
                        <div id="versionProgress" class="progress">
                            <div id="versionProgressBar" class="progress-bar progress-bar-info"></div>
                        </div>
                        <!-- Uploaded files -->
                        <div id="versionFiles" class="files"></div>

                        <div id="versionFilesUploaded"></div>
                    </div>
                </div>
            </div>
        }
 
    </div>
    @Html.ValidationSummary(true)

</div>
    